version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: customer_data
    description: "A dbt model for customer data"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
        tests:
          - unique
          - not_null

      - name: customer_name
        description: "Name of the customer"
        tests:
          - not_null

      - name: email
        description: "Email address of the customer"
        tests:
          - not_null
          - accepted_values: ['email']

      - name: registration_date
        description: "Date when the customer registered"
        tests:
          - not_null
          - accepted_values: ['date']

      - name: total_purchase_amount
        description: "Total amount spent by the customer"
        tests:
          - not_null
          - accepted_values: ['numeric']

  - name: product
    description: "A dbt model for product data"
    columns:
      - name: product_id
        description: "Unique identifier for the product"
        tests:
          - unique
          - not_null

      - name: product_name
        description: "Name of the product"
        tests:
          - not_null

      - name: category
        description: "Category of the product"
        tests:
          - not_null

      - name: price
        description: "Price of the product"
        tests:
          - not_null
          - accepted_values: ['numeric']

      - name: stock_quantity
        description: "Stock quantity of the product"
        tests:
          - not_null
          - accepted_values: ['numeric']
